Added Gunicorn in requirements and README
ScribaSSU/scriba-custom-events pull request #9
Opened 2021-02-26 18:53 UTC by AlekseiVoron

Попробовал запустить приложение через Gunicorn. Получилось.

TODO:
- [ ] попробовать настроить работу логгинга при запуске через Gunicorn (сейчас при описанном в README запуске логи пишутся в консоль, а не в файл, как при запуске через чистый Flask)
- [ ] разобраться с ошибками, которые выдаёт Gunicorn (ошибки не мешают приложению, но... существуют)
- [ ] попробовать поставить вместе с NGINX (для этого нужен сервер)

2021-02-26 21:26 UTC, MagnificentChari commented on README.md
> +Scriba Custom Evants (or SCE) is an additional tool for [Scriba Bot](https://github.com/ScribaSSU).
Scriba Custom Evеnts (or SCE) is an _additional tool_ (звучит странно, мне кажется, что нужно другое словосочетание, но я пока не могу понять, какое) for [Scriba Bot] (https://github.com/ScribaSSU).

2021-02-26 21:30 UTC, MagnificentChari commented on README.md
> +# How to start server
How to start **_a_** server

2021-02-26 21:32 UTC, MagnificentChari commented on README.md
> +1. Move into the project root directory:
Move into the **_project's_** root directory:

2021-02-26 21:39 UTC, MagnificentChari commented on README.md
> +3. Open http://127.0.0.1:5000 into your browser and use SCE.
Open http://127.0.0.1:5000 **_in_** your browser and use SCE.

2021-02-26 21:40 UTC, MagnificentChari commented on README.md
> +1. Move into the project root directory:
1. Move into the **_project's_** root directory:

2021-02-26 21:40 UTC, MagnificentChari commented on README.md
> +2. Start a local server with follow command
Start a local server _**with the following**_ command

2021-02-26 21:43 UTC, MagnificentChari commented on README.md
> +where `SCRIPT_NAME` is an environmental variable which allow use application paths
where `SCRIPT_NAME` is an environmental variable which _**allows to use**_ application paths

2021-02-26 21:45 UTC, MagnificentChari commented on README.md
> +with the permanent prefix (`/sce` in this case).
with _**a**_ permanent prefix

2021-02-26 21:48 UTC, MagnificentChari commented on README.md
> +Option `-w N` runs application on `N` working processes.
Option `-w N` runs **_the_** application on `N` **_worker processes_** .

2021-02-26 21:54 UTC, MagnificentChari commented on README.md
> +Option `-b <ip_address>:<port>` specifies address and port for application
Option `-b <ip_address>:<port>` specifies **_the_** address and **_the_** port for **_the_** application.

2021-02-26 21:58 UTC, MagnificentChari commented on README.md
> +3. Open http://localhost:5000/sce into your browser and use SCE.
3. Open http://localhost:5000/sce **_in_** your browser and use SCE.

2021-02-26 21:59 UTC, MagnificentChari requested changes
Добавил комментарии с фиксами для ингриша.

2021-03-05 16:42 UTC, Dimasique approved these changes

2021-03-05 16:42 UTC, MagnificentChari approved these changes

2021-03-05 16:47 UTC, merged